Add support for pip 8.x
Pip 8 has deprecated the `--allow-external`, `--allow-unverified` and
`--allow-all-external` options, since they they now a no-op after
changes to PyPI, even with older versions of pip:
https://github.com/pypa/pip/pull/3070#issuecomment-137464224

Removing handling for these in peep does not affect older versions of
pip, but avoids an exception for each removed option with pip v8:
TypeError: __init__() got an unexpected keyword argument 'allow_unverified'

Fixes #112.